// ─── catalogue-emitter.mjs ───────────────────────────────────────────────────
// Serialises a Product[] into packages/shared/src/catalogue/products.generated.ts.
//
// Extracted from generate-catalogue.mjs so that the same emitter serves two
// producers, and the file they write is byte-identical whichever one ran:
//
//   generate-catalogue.mjs        products.ts + Supabase  (the normal path)
//   bake-catalogue-from-source.mjs   products.ts alone    (no database needed)
//
// Keeping one emitter is the point. Two copies would drift, and a drift here
// shows up as a spurious whole-file diff on the next regeneration, which is
// exactly the kind of noise that gets a generated file waved through in review.

/** Escape a value for a single-quoted TS string literal. */
export function tsString(value) {
  return `'${String(value)
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\r/g, '\\r')
    .replace(/\n/g, '\\n')
    // U+2028/U+2029 are legal inside a TS string literal but end a line for
    // some tooling — escaping them keeps the emitted module portable. Spelled
    // as escapes so this source carries no invisible characters of its own.
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')}'`;
}

/**
 * Serialise to TypeScript source. Every value lands on its own line: a
 * generated file is read as a diff far more often than as a document, and
 * one-value-per-line means an admin price edit shows up as exactly one changed
 * line in review. Keys are emitted bare — every key in the Product shape is a
 * valid identifier, so none of them need quoting.
 */
export function tsValue(value, indent) {
  const pad = '  '.repeat(indent);
  const padInner = '  '.repeat(indent + 1);
  if (typeof value === 'string') return tsString(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`Non-finite number: ${value}`);
    return String(value);
  }
  if (Array.isArray(value)) {
    if (!value.length) return '[]';
    const items = value.map((v) => `${padInner}${tsValue(v, indent + 1)},`).join('\n');
    return `[\n${items}\n${pad}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value);
    if (!entries.length) return '{}';
    const body = entries.map(([k, v]) => `${padInner}${k}: ${tsValue(v, indent + 1)},`).join('\n');
    return `{\n${body}\n${pad}}`;
  }
  throw new Error(`Unserialisable value: ${String(value)}`);
}

/**
 * @param products  the catalogue to emit
 * @param origin    one line naming where the rows came from, so a reader of the
 *                  generated file can tell a database bake from a source bake
 *                  without diffing it against the shop.
 */
export function renderModule(products, origin = 'the Supabase `products` + `variants` tables, read with the anon key.') {
  const variantCount = products.reduce((n, p) => n + p.variants.length, 0);
  const header = [
    '// ─── Baked catalogue — GENERATED, do not edit by hand ────────────────────',
    '// Generated by: pnpm run generate:catalogue  (scripts/generate-catalogue.mjs)',
    `// Source: ${origin}`,
    `// Contents: ${products.length} products · ${variantCount} variants (SKUs).`,
    '//',
    '// Edits made in /admin land here on the next build, which is how a static',
    '// export shows database content at all. Editing this file by hand instead',
    '// will be silently reverted by the next deploy — change the product in the',
    '// admin (or in products.ts, for the hardcoded fallback) and regenerate.',
    '//',
    '// Committed on purpose, matching supabase/migrations/0014_seed_products.sql:',
    '// a build with no database reachable still ships the last known-good shop.',
    '',
    "import type { Product } from '../types/product';",
    '',
  ].join('\n');
  const body = products.map((p) => `  ${tsValue(p, 1)},`).join('\n');
  return `${header}export const GENERATED_CATALOGUE: Product[] = ${
    products.length ? `[\n${body}\n]` : '[]'
  };\n`;
}
