-- ─── 0021 · Product photography — GENERATED, do not edit by hand ──────────
-- Generated by: node --import tsx scripts/photography/emit-image-migration.mjs
-- Source: packages/shared/src/catalogue/products.ts (HARDCODED_CATALOGUE)
--
-- The Khammam photography drop of 2026-08-13, applied to rows that already
-- exist. 0014_seed_products.sql inserts any product the database is missing
-- with its images attached, but it is `on conflict do nothing`, so it cannot
-- fill in the images of a product that was seeded back in April. This does.
--
-- GUARDED: only rows with no usable image are touched, so an admin upload made
-- after this migration was written survives it. Re-running is therefore safe
-- and idempotent — the second run matches nothing.
--
-- 111 products carry a photograph. The rest keep the placeholder on
-- purpose: the drop contained no pickle jar, no podi and no loose nuts. See
-- STILL_UNSHOT in scripts/photography/shot-list.mjs for the next shoot's brief.
begin;

update public.products as p
set images = v.images
from (values
    ('badam-ki-jali', '[{"url":"/products/badam-butter-burfi.webp","alt":"Badam Butter Burfi from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('khubani-dry-fruit-mithai', '[{"url":"/products/dry-fruit-halwa.webp","alt":"Dry Fruit Halwa from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('kaju-katli', '[{"url":"/products/kaju-katli.webp","alt":"Kaju Katli diamonds fanned into a star on red cloth, one piece leafed with edible silver, whole cashews scattered beside them","width":1400,"height":1400}]'::jsonb),
    ('gulab-jamun', '[{"url":"/products/gulab-jamun.webp","alt":"Three deep-brown Gulab Jamun, each topped with slivered almond, resting close together on a pale dish","width":1400,"height":1400}]'::jsonb),
    ('motichoor-ladoo', '[{"url":"/products/motichoor-ladoo.webp","alt":"Motichoor Ladoos with saffron pearls visible across the surface","width":1400,"height":1400},{"url":"/products/motichoor-ladoo-2.webp","alt":"Four Motichoor Ladoos heaped in a blue-and-white painted bowl against a pink backdrop","width":1400,"height":1400}]'::jsonb),
    ('hyderabadi-mixture', '[{"url":"/products/navaratna-mixture.webp","alt":"Navaratna Mixture from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('peanut-chivda', '[{"url":"/products/atukula-mixture.webp","alt":"Atukula Mixture from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('besan-sev', '[{"url":"/products/karapusa.webp","alt":"Karapusa — Crispy Karapusa from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('chai-time-combo', '[{"url":"/products/navaratna-mixture.webp","alt":"Navaratna Mixture from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('festival-essentials-combo', '[{"url":"/products/dussehra-gift-box.webp","alt":"Dussehra Gift Box from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('diwali-premium-hamper', '[{"url":"/products/diwali-premium-hamper.webp","alt":"A woven gift basket packed with a tray of assorted sweet bites, dry-fruit pouches, painted clay diyas and wrapped chocolate bars","width":1400,"height":1400}]'::jsonb),
    ('classic-gifting-box', '[{"url":"/products/dry-fruits-gift-hamper.webp","alt":"Dry Fruits Gift Hamper from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('corporate-essentials-box', '[{"url":"/products/dry-fruits-gift-hamper.webp","alt":"Dry Fruits Gift Hamper from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('raksha-bandhan-thali', '[{"url":"/products/raksha-bandhan-thali.webp","alt":"An open green gift box holding a beaded rakhi, wrapped sweets and foil-wrapped chocolates, staged on a mother-of-pearl tray","width":1400,"height":1400}]'::jsonb),
    ('eid-signature-box', '[{"url":"/products/diwali-premium-hamper.webp","alt":"Diwali Premium Hamper from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('wedding-trousseau-box', '[{"url":"/products/diwali-premium-hamper.webp","alt":"Diwali Premium Hamper from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('pongal-pot-set', '[{"url":"/products/dussehra-gift-box.webp","alt":"Dussehra Gift Box from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('office-chai-tray', '[{"url":"/products/karapusa.webp","alt":"Karapusa — Crispy Karapusa from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('atukula-mixture', '[{"url":"/products/atukula-mixture.webp","alt":"Atukula Mixture — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('chegodilu', '[{"url":"/products/chegodilu.webp","alt":"Chegodilu — Crispy Chegodilu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('chekkalu', '[{"url":"/products/chegodilu.webp","alt":"Chegodilu — Crispy Chegodilu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('cornflakes-mixture', '[{"url":"/products/cornflakes-mixture.webp","alt":"Cornflakes Mixture — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('dal-mudi-snacks', '[{"url":"/products/atukula-mixture.webp","alt":"Atukula Mixture from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('janthikalu', '[{"url":"/products/murukulu.webp","alt":"Murukulu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('kara-boondhi', '[{"url":"/products/navaratna-mixture.webp","alt":"Navaratna Mixture from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('karapusa', '[{"url":"/products/karapusa.webp","alt":"Karapusa — Crispy Karapusa — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('masala-kaju', '[{"url":"/products/masala-kaju.webp","alt":"Masala Kaju — Spicy Cashew — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('masala-palli', '[{"url":"/products/palli-pakodi.webp","alt":"Palli Pakodi — Crispy Peanut Pakodi from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('murukulu', '[{"url":"/products/murukulu.webp","alt":"Murukulu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('onion-ribbon-pakodi', '[{"url":"/products/masala-pakodi.webp","alt":"Masala Pakodi from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('palli-pakodi', '[{"url":"/products/palli-pakodi.webp","alt":"Palli Pakodi — Crispy Peanut Pakodi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('pappu-chekkalu', '[{"url":"/products/chegodilu.webp","alt":"Chegodilu — Crispy Chegodilu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('pappu-chekodi', '[{"url":"/products/chegodilu.webp","alt":"Chegodilu — Crispy Chegodilu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('navaratna-mixture', '[{"url":"/products/navaratna-mixture.webp","alt":"Navaratna Mixture — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('masala-pakodi', '[{"url":"/products/masala-pakodi.webp","alt":"Masala Pakodi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kaju-pakodi', '[{"url":"/products/kaju-pakodi.webp","alt":"Kaju Pakodi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('gorumitulu', '[{"url":"/products/gorumitulu.webp","alt":"Gorumitulu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kachuralu', '[{"url":"/products/kachuralu.webp","alt":"Kachuralu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('sanagalu', '[{"url":"/products/sanagalu.webp","alt":"Sanagalu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('vamu-poosa', '[{"url":"/products/vamu-poosa.webp","alt":"Vamu Poosa — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('butterscotch-bites', '[{"url":"/products/butterscotch-bites.webp","alt":"Butterscotch Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('choco-bites', '[{"url":"/products/choco-bites.webp","alt":"Choco Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kaju-bites', '[{"url":"/products/kaju-bites.webp","alt":"Kaju Bites — photographed at the Khammam kitchen","width":1400,"height":1400},{"url":"/products/kaju-bites-2.webp","alt":"Kaju Bites — additional view 2","width":1400,"height":1400}]'::jsonb),
    ('kesar-bites', '[{"url":"/products/mango-delight.webp","alt":"Mango Delight from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('khajoor-bites', '[{"url":"/products/royal-nutty-dates.webp","alt":"Royal Nutty Dates from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('mango-crunch-bites', '[{"url":"/products/kacha-mango-delight.webp","alt":"Kacha Mango Delight from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('mixed-bites', '[{"url":"/products/tutti-frutti-bites.webp","alt":"Tutti Frutti Bites from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('oreo-bites', '[{"url":"/products/oreo-bites.webp","alt":"Oreo Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('pineapple-bites', '[{"url":"/products/pineapple-bites.webp","alt":"Pineapple Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('silky-bites', '[{"url":"/products/silky-bites.webp","alt":"Silky Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('strawberry-bites', '[{"url":"/products/cranberry-bites.webp","alt":"Cranberry Bites from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('tutti-frutti-bites', '[{"url":"/products/tutti-frutti-bites.webp","alt":"Tutti Frutti Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('anjeer-bites', '[{"url":"/products/anjeer-bites.webp","alt":"Anjeer Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('cranberry-bites', '[{"url":"/products/cranberry-bites.webp","alt":"Cranberry Bites — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('mango-delight', '[{"url":"/products/mango-delight.webp","alt":"Mango Delight — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kacha-mango-delight', '[{"url":"/products/kacha-mango-delight.webp","alt":"Kacha Mango Delight — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('pan-shots', '[{"url":"/products/pan-shots.webp","alt":"Pan Shots — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('royal-nutty-dates', '[{"url":"/products/royal-nutty-dates.webp","alt":"Royal Nutty Dates — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('anjeer-whole', '[{"url":"/products/anjeer-bites.webp","alt":"Anjeer Bites from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('cranberry', '[{"url":"/products/cranberry-bites.webp","alt":"Cranberry Bites from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('booster-laddu', '[{"url":"/products/booster-laddu.webp","alt":"Booster Laddu — Energy Dry-Fruit Laddu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('dry-fruit-laddu', '[{"url":"/products/dry-fruit-laddu.webp","alt":"Dry Fruit Laddu — Protein-Rich — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('gondh-laddu', '[{"url":"/products/annamayya-laddu.webp","alt":"Annamayya Laddu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('high-protein-laddu', '[{"url":"/products/booster-laddu.webp","alt":"Booster Laddu — Energy Dry-Fruit Laddu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('millet-laddu', '[{"url":"/products/rava-laddu.webp","alt":"Rava Laddu from the Ravi Sweets counter","width":1400,"height":1400}]'::jsonb),
    ('nuvvula-laddu', '[{"url":"/products/nuvvula-laddu.webp","alt":"Nuvvula Laddu — Bone-Strengthening Sesame Laddu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('bournvita-biscuits', '[{"url":"/products/bournvita-biscuits.webp","alt":"Bournvita Biscuits — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('coconut-biscuits', '[{"url":"/products/coconut-biscuits.webp","alt":"Coconut Biscuits — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kaju-biscuits', '[{"url":"/products/kaju-biscuits.webp","alt":"Kaju Biscuits — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('moon-biscuits', '[{"url":"/products/moon-biscuits.webp","alt":"Moon Biscuits — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('plain-kalakand', '[{"url":"/products/plain-kalakand.webp","alt":"Plain Kalakand — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('loose-kalakand', '[{"url":"/products/loose-kalakand.webp","alt":"Loose Kalakand — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('ajmer-kalakand', '[{"url":"/products/ajmer-kalakand.webp","alt":"Ajmer Kalakand — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('badam-pista-kalakand', '[{"url":"/products/badam-pista-kalakand.webp","alt":"Badam Pista Kalakand — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('bournvita-kalakand', '[{"url":"/products/bournvita-kalakand.webp","alt":"Bournvita Kalakand — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kaju-kalakand', '[{"url":"/products/kaju-kalakand.webp","alt":"Kaju Kalakand — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('chitti-kova', '[{"url":"/products/chitti-kova.webp","alt":"Chitti Kova — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('special-kova', '[{"url":"/products/special-kova.webp","alt":"Special Kova — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kova-billalu', '[{"url":"/products/kova-billalu.webp","alt":"Kova Billalu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('peda', '[{"url":"/products/peda.webp","alt":"Peda — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('mango-cream', '[{"url":"/products/mango-cream.webp","alt":"Mango Cream — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('badam-butter-burfi', '[{"url":"/products/badam-butter-burfi.webp","alt":"Badam Butter Burfi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('jalebi', '[{"url":"/products/jalebi.webp","alt":"Jalebi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('paneer-jalebi', '[{"url":"/products/paneer-jalebi.webp","alt":"Paneer Jalebi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('badusha', '[{"url":"/products/badusha.webp","alt":"Badusha — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('baklava', '[{"url":"/products/baklava.webp","alt":"Baklava — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('bellam-gavvalu', '[{"url":"/products/bellam-gavvalu.webp","alt":"Bellam Gavvalu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('bobbattu', '[{"url":"/products/bobbattu.webp","alt":"Bobbattu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('gujiya', '[{"url":"/products/gujiya.webp","alt":"Gujiya — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kajjikayalu', '[{"url":"/products/kajjikayalu.webp","alt":"Kajjikayalu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kova-kajjikayalu', '[{"url":"/products/kova-kajjikayalu.webp","alt":"Kova Kajjikayalu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('gottam-kaja', '[{"url":"/products/gottam-kaja.webp","alt":"Gottam Kaja — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('madatha-kaja', '[{"url":"/products/madatha-kaja.webp","alt":"Madatha Kaja — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('poornalu', '[{"url":"/products/poornalu.webp","alt":"Poornalu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('sajja-burelu', '[{"url":"/products/sajja-burelu.webp","alt":"Sajja Burelu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kobbari-burelu', '[{"url":"/products/kobbari-burelu.webp","alt":"Kobbari Burelu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('pootharekulu', '[{"url":"/products/pootharekulu.webp","alt":"Pootharekulu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('sweet-boondi', '[{"url":"/products/sweet-boondi.webp","alt":"Sweet Boondi — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('mysore-pak', '[{"url":"/products/mysore-pak.webp","alt":"Mysore Pak — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('ghee-mysore-pak', '[{"url":"/products/ghee-mysore-pak.webp","alt":"Ghee Mysore Pak — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kaju-bullets', '[{"url":"/products/kaju-bullets.webp","alt":"Kaju Bullets — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('kaju-chikki', '[{"url":"/products/kaju-chikki.webp","alt":"Kaju Chikki — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('bombay-halwa', '[{"url":"/products/bombay-halwa.webp","alt":"Bombay Halwa — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('pineapple-halwa', '[{"url":"/products/pineapple-halwa.webp","alt":"Pineapple Halwa — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('dry-fruit-halwa', '[{"url":"/products/dry-fruit-halwa.webp","alt":"Dry Fruit Halwa — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('besan-laddu', '[{"url":"/products/besan-laddu.webp","alt":"Besan Laddu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('rava-laddu', '[{"url":"/products/rava-laddu.webp","alt":"Rava Laddu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('ganesh-laddu', '[{"url":"/products/ganesh-laddu.webp","alt":"Ganesh Laddu — photographed at the Khammam kitchen","width":1400,"height":1400},{"url":"/products/ganesh-laddu-2.webp","alt":"Ganesh Laddu — additional view 2","width":1400,"height":1400}]'::jsonb),
    ('annamayya-laddu', '[{"url":"/products/annamayya-laddu.webp","alt":"Annamayya Laddu — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('dry-fruits-gift-hamper', '[{"url":"/products/dry-fruits-gift-hamper.webp","alt":"Dry Fruits Gift Hamper — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb),
    ('dussehra-gift-box', '[{"url":"/products/dussehra-gift-box.webp","alt":"Dussehra Gift Box — photographed at the Khammam kitchen","width":1400,"height":1400}]'::jsonb)
) as v(slug, images)
where p.slug = v.slug
  and not exists (
    select 1
    from jsonb_array_elements(coalesce(p.images, '[]'::jsonb)) as img
    where coalesce(img ->> 'url', '') <> ''
  );

commit;
